version:  '3.0'
services:
  nginx:
    build: ./dockerfiles/nginx/
    ports:
      - "80:80"
    links:
      - "php-fpm:php-fpm"
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
    restart: always
    expose:
      - "80"
    command: nginx -g 'daemon off;'
  mysql-db:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d:ro
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: zhaojun
        MYSQL_DATABASE: oeynet_client_bbs
        MYSQL_USER: zhaojun
        MYSQL_PASSWORD: zhaojun
  redis-db:
    build: ./dockerfiles/redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data/redis:/data
  php-fpm:
    build: ./dockerfiles/php/
    restart: always
    environment:
        PHP_APP_DEBUG: 'true'
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw

    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    command: php-fpm
  composer:
    image: composer:1.4.2
    volumes:
    #网站目录
      - ./app:/app:rw
    working_dir: /app/webroot
    command: composer install
  bower:
    image: digitallyseamless/nodejs-bower-grunt
    volumes:
    #网站目录
      - ./app:/app:rw
    working_dir: /app/webroot
    command: bower install

##GoogleDocker资源监控
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
# 启动一次备份服务 ./docker-compose restart backup
  backup:
    image: mysql:5.7
    environment:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: oeynet_client_bbs
        MYSQL_USER: root
        MYSQL_PASSWORD: zhaojun
    depends_on:
      - mysql-db
    links:
      - mysql-db:mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/backup:/backup:rw
      - ./dockerfiles/backup/:/app:ro
    entrypoint:
      - /bin/bash
    command: /app/backup-default.sh

volumes:
  app-data:
