version:  '3.0'
services:
  nginx:
    image: nginx:1.13.3
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php-fpm"
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dockerfiles/nginx/certs:/etc/nginx/certs:ro
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
    depends_on:
      - redis-db
    networks:
      - front-net
    restart: always
    command: nginx -g 'daemon off;'
  mysql-db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    networks:
      - back-net
    environment:
        MYSQL_ROOT_PASSWORD: zhaojun
        MYSQL_DATABASE: package_v1
        MYSQL_USER: zhaojun
        MYSQL_PASSWORD: zhaojun
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  redis-db:
    build: ./dockerfiles/redis
    restart: always
    networks:
      - back-net
    volumes:
      - ./data/redis:/data
  php-fpm:
    build: ./dockerfiles/php/
    image: zhaojunlike/php-fpm:5.6
    restart: always
    networks:
      - front-net
      - back-net
    environment:
        DEV_APP_DEBUG: 1
        APP_DEBUG: 1
        APP_TRACE: 1
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    depends_on:
      - mysql-db
      - redis-db
    links:
      - mysql-db
      - redis-db
    command: php-fpm
networks:
  front-net:
  back-net:
volumes:
  app-data:

