version:  '3.0'
services:
  nginx:
    image: nginx:1.13.3
    volumes:
#网站目录
      - ./app:/var/www/html
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d:ro
#日志文件
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: any
    command: nginx -g 'daemon off;'

  mysql-db:
    image: mysql:5.7
#很重要导入到处数据
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
        MYSQL_ROOT_PASSWORD: zhaojun
        MYSQL_DATABASE: lottery_api_sale
        MYSQL_USER: zhaojun
        MYSQL_PASSWORD: zhaojun
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: any

  redis-db:
    image: redis
    volumes:
      - ./data/redis:/data
    deploy:
      restart_policy:
        condition: any
##
  php-fpm:
    image: zhaojunlike/php-fpm:5.6
    volumes:
#网站目录
      - ./app:/var/www/html:rw
#配置文件
      - ./dockerfiles/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro

#挂载站点日志
      - ./logs/php-fpm:/var/log/php-fpm:rw
    deploy:
      restart_policy:
        condition: any
    command: php-fpm

##附加扩展安装器
  composer:
    image: composer:1.4.2
    volumes:
      - ./app:/app:rw
    working_dir: /app/webroot
    deploy:
      restart_policy:
        condition: none
    command: composer install

  bower:
    image: digitallyseamless/nodejs-bower-grunt
    volumes:
      - ./app:/app:rw
    working_dir: /app/webroot
    deploy:
      restart_policy:
        condition: none
    command: bower install

##集群监控
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
##第一次迁移数据所需的镜像 version0.3 README手动迁移
#  mysql-database:
#    image: mysql:5.7
#    volumes:
#      - ./data/backup:/data/backup

##GoogleDocker资源监控
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  wwwroot:
    driver: local