version:  '3.0'
services:
  composer:
    #image: composer:1.4.2
    image: zhaojunlike/composer:5.6-latest
    volumes:
      - ./app:/app:rw
    working_dir: /app/webroot
    command: "composer update"